# Generated by Django 4.2.9 on 2024-12-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("f1", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="constructorstandings",
            table="constructorStandings",
        ),
    ]
